---
title: "Week 1 Notes - Course Introduction"
date: "2025-09-08"
---

## Key Concepts Learned
- [What is Git, Github, Quarto, and full term for YAML.]
- [Some basic R coding language and went over an example on CAR data.]

## Coding Techniques
- [ **Bold text**
    *Italic text*
    ***Bold and italic***
    `code text`
    ~~Strikethrough~~
    select() - choose columns
    filter() - choose rows
    mutate() - create new variables
    summarize() - calculate statistics
    group_by() - operate on groups]
- [ ---
    title: "My Analysis" 
    author: "Your Name"
    date: today
    format: html
    ---]

## Questions & Challenges
- [I think it is hard to understand all the R code and notations.]
- [This is my first time interact with R and Github. So I need to try everything first and I will find more challenges.]

## Connections to Policy
- [Both the analysis and the data itself can be biased. The reason is that data were collected by someone who might be biased.]

## Reflection
- [Quarto is really interesting. Looking forward to see more what Quarto can do.]
- [Through our assignment.]
